apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/

images:
  - name: nginx
    newName: my-registry/nginx
    newTag: 1.22.0
  - name: redis
    newTag: 7.2.0
    digest: sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
  - name: app
    newName: myorg/app
    newTag: latest
